services:
  mysql:
    image: mysql:8.0
    container_name: spring-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cookies_db
      MYSQL_USER: cookies_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"