services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cookies_db
      MYSQL_USER: cookies_user
      MYSQL_PASSWORD: password
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 1s
    ports:
      - "3306:3306"
    networks:
      - app_network

  cookies-web-app:
    image: cookies-web-app:latest
    container_name: cookies-web-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cookies_db
      SPRING_DATASOURCE_USERNAME: cookies_user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app_network

networks:
  app_network:
    driver: bridge