create TABLE cookies
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    identityId varchar(64) NOT NULL,
    flavor     varchar(64) NOT NULL,
    amount     INTEGER     NOT NULL,
);