name: Run Tests

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant Execute Permission to Gradlew
        run: chmod +x ./gradlew

      - name: Build and Test with Gradle
        run: ./gradlew clean test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: Test Report
#        uses: dorny/test-reporter@v1
#        if: success() || failure()    # run this step even if previous step failed
#        with:
#          name: JEST Tests            # Name of the check run which will be created
#          path: build/test-results/**/*.xml    # Path to test results
#          reporter: java-junit        # Format of test results
